### PR TITLE
Backport (+rel. adaptat.) monitor option to zmq flesnet

### PR DESCRIPTION
**Pull request by PALoizeau**
We realized while trying to provide the full `influx+grafana` info to the mobile setup used by the MUCH team at GIF/CERN that we never ported back the monitoring improvements from the `rdma` version of the `flesnet` binary to the `zmq` one.
The `cri-status` part worked flawlessly.

It would probably be good to have this to help detector groups have better control of their various lab/cosmics/beamtime setups.

For now only copy-paste with the necessary edits to have it compiling.

Before leaving `Draft` state, needs at least:

- Testing with a real setup
- Cleanup to make sure all fields are relevant/properly filled in zmq context (info space, no zmq object)

Planned additions before merging, but only when I find time or if detector groups show strong/urgent interest:

- HowTos in the `doc` folder for Influx v1.x and v2.x including 
  - Setup instructions for Influx and Grafana (InfluxQL connection toward v1 or v2 DBs)
  - Default names for databases and DB connections to simplify Grafana Dashboard import
  - Default/example console setup and commands for `cri-status`, `flesnet` and `tsclient` for Influx v1.x and Influx v2.x
  - Raw info at in our [Redmine mCBM Wiki](https://redmine.cbm.gsi.de/projects/mcbm/wiki/Standalone_CRI_flesnet_Influx_v2-Grafana_v10_setup) (Behind Weblogin)
- Portable JSON grafana dashboards in `contrib` folder/sub-folder 
  - matching those default DB connection names, maybe only compatible with newer version of Grafana
  - without the eLOG interface (or with two versions w/ and w/o)

### CODE REVIEW

**Comment by cuveland** [comment]
@PALoizeau Thank you. This looks really good and straightforward.

I am sorry that I did not comment earlier. How shall we proceed? I did not test the code. But I would be surprised if it affected the operation at all if turned off. So I would not hesitate too much to just merge it as it is. It would be sad to have your work not included. On the other hand, the items you raise in the text above include substantial additional work. What do you think?

**Comment by PALoizeau** [comment]
@cuveland I think without the two planned addition there would be a risk that some users try to get it running but fail and come asking us, especially for the Grafana dashboards (it can be quite confusing when only half of the DB accesses work), which would probably cost us more time.

As there was also no strong push from any detector group yet, I put this on the back-burner until I have the time to at least add the instructions and the JSON files.
The testing phase could probably be skipped by adding a printout on startup that this is still experimental.

Who knows, maybe I will manage to do this faster than I thought during the Collaboration meeting breaks (^^)'

**Comment by PALoizeau** [comment]
Added the portable JSON and the HowTo file + filled it with the some info from  the GIF++ efforts (Influx v2) and previous work on the eTOF manual monitoring (Influx v1 config)

Still not tested, I was mostly pushed by my token soon to come expiration :sweat_smile:

**Comment by PALoizeau** [comment]
Got a tester with Esteban and one of the standalone setups in Heidelberg, we will validate/fix this next week

**Comment by PALoizeau** [comment]
Tested on cbmin008 in the Heidelberg TOF setup:
- Standard names for Influx v1 databases
- Influx v1 emission with ZMQ connections
- Standard names for Grafana connections to Influx v1 databases
- Generic dashboards importation using these standard names

Not tested:
- Installation of Influxv1 and Grafana (existing dockerized instance available)

=> Rebased and did minor fixes in one dashboard and in the documentation, but otherwise worked flawlessly

Most graphs seem to make sense and behave as expected in terms of "shapes", including those on the input buffers. Cannot say anything on the units or actual values as I am no expert

If you want to test it and check it more in detils, I left coarse instructions in the home folder under `HowTo_FlesnetMonitoring_2023_10_27.txt`
=> In this case please coordinate with Esteban Rubio to avoid interferences.

**Pull request merged**
