### PR TITLE
Include libfabric in default build flow and fix CI

### PR DESCRIPTION
**Pull request by fsalem**
When fles_libfabric is included, the build always fails. The reason is an error related to 'out of memory' errors. I propose limiting parallel processes up to 32

### CODE REVIEW

**Comment by oTTer-Chief** [comment]
Hi @fsalem ,

I tested your branch on my dev machine. It compiles now also with libfabric. Looks like the missing header fixed it.
However there are some `ISO C++ forbids variable length array` warnings. They also show up I the CI. Could you please fix them or silence them if you consider it false positives.

**Comment by fsalem** [comment]
Hi @oTTer-Chief,

Yes, this header file fixed the compilation problem when Libfabric 1.6 is used, which is not the case with recent releases. However, even after considering this fix, the build always failed once fles_libfabric is included and it was due to memory limitations. 

I fixed the warnings and the build is now free of warnings.

**Review by cuveland — COMMENTED** [review]
Where is the corresponding "delete" to these "new" statements?
May this be a memory leak?

**Comment by fsalem** [comment]
@cuveland sorry, I forgot to use smart pointers. I will update it and send another PR.

**Pull request merged**
